---
title: "LAB#SE01-1"
categories: [javase, lab]
---
# Maven/Gradle Person and Account

::: {.panel-tabset}
## Context
**Basic understanding of Java programming language is required**, as well as some familiarity with **Maven or Gradle for managing dependencies** and building the project.

**Knowledge of algotighms and data structures** to implement the required classes.

## Goal
**Create three classes in Java** (`Person`, `Account` and `Manager`) that implement different algorightms or data structures.

**Test these classes** using JUnit.

## Tasks
(@) Create **a new Maven or Gradle project** and setting up the project structure
(@) Modify the project's `pom.xml` or `build.gradle` file to import necessary dependencies, including **JUnit** for testing
(@) Implement the three required classes in Java
(@) Implement two basic patter-designs: **singleton** and **think about factory**
(@) Write **JUnit tests** to verify that classes work as expected

## Optional
*   **Allow the user to input data via the console**, rather than using `hard-coded test data` in JUnit tests
:::

## Approach 1
### UML diagram
:::{.callout-note collapse="false"}
```{mermaid}
classDiagram
    Person "1" --o "1" Account : has
    Person "*" -- "1" AccountManager : manages

    class Person{
        -String name
        -String address
        -int age
        -Account account

        +getBalance()
        +setBalance()
        +getPin()
        +setPin()
    }
    
    class Account{
        -String accountManager
        -String pin
        -double balance

        +equals(Account compared) boolean
    }

    class AccountManager{
        +withdrawal(Person person, double amount) boolean
        +transfer(Person sender, Person receiver, double amount) boolean
        +changePin(Person person, String oldPin, String newPin) boolean
    }
    <<Static>> AccountManager
    %%note for AccountManager "Can withdraw money from a person's account\nCan tranfer money between two persons' account\nCan change the Pin of a person's account"
```
:::

### Classes specification
#### Person
:::{.callout-note collapse="true"}
## Person class
```{.java include="../../../../java-exercises/lab-se-01-1/approach_1/src/main/java/org/labSe01Part1/Person.java"}

```
:::

#### Account
:::{.callout-note collapse="true"}
## Account class
```{.java include="../../../../java-exercises/lab-se-01-1/approach_1/src/main/java/org/labSe01Part1/Account.java"}

```
:::

#### AccountManager
:::{.callout-note collapse="true"}
```{.java include="../../../../java-exercises/lab-se-01-1/approach_1/src/main/java/org/labSe01Part1/AccountManager.java
```
:::

## Approach 2

The `AccountManager` class is created as a `Singleton` to force its usage when managing accounts.

### UML diagram
:::{.callout-note collapse="false"}
```{mermaid}
classDiagram
    class Account {
        -String accountNumber
        -String pin
        -double balance

        +getAccountNumber()
        +setAccountNumber()
        +getPin()
        +setPin()
        +getBalance()
        +setBalance()
    }

    class Person {
        -String name
        -int age
        -String address
        -Account account

        +getName()
        +setName()
        +getAge()
        +setAge()
        +getAddress()
        +setAddress()
        +getAccount()
        +setAccount()
        +getBalance()
        +setBalance()
        +getPin()
        +setPin()
    }

    %% AccountManager Singleton
    class AccountManager {
        +getInstance()
        +withdrawal(Person client, double amount)
        +transfer(Person sender, Person receiver, double amount)
        +deposit(Person client, double amount)
        +changePin(Person client)
    }

    <<Singleton>> AccountManager
    %% Classes relationships
    Person "1" --o "1" Account : has
    Person "*" -- "1" AccountManager : manages
```
:::

### Classes specifications
#### Person
:::{.callout-note collapse="true"}
```{.java include="../../../../java-exercises/lab-se-01-1/approach_2/src/main/java/org/labSe01Part1/Person.java"}

```
:::
#### Account
:::{.callout-note collapse="true"}
```{.java include="../../../../java-exercises/lab-se-01-1/approach_2/src/main/java/org/labSe01Part1/Account.java"}

```
:::
#### AccountManager
:::{.callout-note collapse="true"}
```{.java include="../../../../java-exercises/lab-se-01-1/approach_2/src/main/java/org/labSe01Part1/AccountManager.java"}

```
:::

## Approach 3 - Singleton + Hashmaps

Another approach would be that a client might have multiple accounts. We can manage all the client's accounts as a `HashMap` where its keys are the account's owners (`Person`) and each value is a list of accounts (`Account`). This way we are decoupling classes Account and Person.

The `AccountManager` class is created as a `Singleton` to force its usage when managing accounts.

### UML diagram
:::{.callout-note collapse="false"}
```{mermaid}
classDiagram
    class Person {
        -String name
        -int age
        -String address

        +getName()
        +setName()
        +getAge()
        +setAge()
        +getAddress()
        +setAddress()
        +equals(Person compared) boolean
    }

    class Account {
        -String accountNumber
        -String pin
        -double balance

        +getAccountNumber()
        +setAccountNumber()
        +getPin()
        +setPin()
        +getBalance()
        +setBalance()
        +equals(Account compared) boolean
    }

    %% AccountManager Singleton
    class AccountManager {
        -HashMap< Person, ArrayList< Account > > clients

        -getAccount(Person client, String accountNumber)
        -createAccount(Person client, Account newAccount)
        -removeAccount(Person client, Account newAccount)

        -getClient(String clientName)
        -removeClient(Person client)

        -getAccounts(Person client)

        -changePin(Account account, String oldPin, String newPin)

        +getInstance()
        +getClientBalance(String clientName)
        +getAccountBalance(String clientName, String accountNumber)
        +withdrawal(String clientName, String accountNumber, double amount)
        +transfer(String senderName, String senderAccountNumber, String receiverName, String receiverAccountNumber, double amount)
        +deposit(String clientName, String accountNumber, double amount)
        +changePin(String clientName, String accountNumber, String oldPin, String newPin)
    }

    <<Singleton>> AccountManager

    %% Classes relationship
    Person "*" -- "1" AccountManager : manages
    Account "*" -- "1" AccountManager : manages
```
:::

### Classes specifications
#### Person
:::{.callout-note collapse="true"}
```{.java include="../../../../java-exercises/lab-se-01-1/approach_3/src/main/java/org/labSe01Part1/Person.java"}

```
:::
#### Account
:::{.callout-note collapse="true"}
```{.java include="../../../../java-exercises/lab-se-01-1/approach_3/src/main/java/org/labSe01Part1/Account.java"}

```
:::
#### AccountManager
:::{.callout-note collapse="true"}
```{.java include="../../../../java-exercises/lab-se-01-1/approach_3/src/main/java/org/labSe01Part1/AccountManager.java"}

```
:::