server:
  port: 9090

spring:
  main:
    banner-mode: off
  security:
    user: protoss
    password: 1234
    roles: user
  application:
    name: spring-lab-0-approach-1
  h2:
    console:
      enabled: 'true'
    datasource:
      username: cifoweb
      password: cifotest
      url: jdbc:h2:../spring-boot-lab-0/h2
      driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher