version: '3.2'
name: nextcloud
services:
  db:
    image: postgres
    #container_name: nextcloud_db
    hostname: nextcloud_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Madrid
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    image: nextcloud:stable-apache
    #container_name: nextcloud_app
    restart: always
    ports:
      - 8081:80
    volumes:
      - data:/var/www/html
    environment:
      - TZ=Europe/Madrid
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=<nextcloud.server.ip> nextcloud.example.com localhost
      # Required fields for Cloudflare HTTPS access
      - OVERWRITEPROTOCOL=https
      #- APACHE_DISABLE_REWRITE_IP=1
      #- TRUSTED_PROXIES=nextcloud.example.com
      # Additional memory increase for both clients and uploads
      #- PHP_MEMORY_LIMIT=1024M
      #- PHP_UPLOAD_LIMIT=1024M
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  db:
  data:

secrets:
  nextcloud_admin_password:
    file: $PWD/secrets/nextcloud_admin_password.txt # put admin password in this file
  nextcloud_admin_user:
    file: $PWD/secrets/nextcloud_admin_user.txt # put admin username in this file
  postgres_db:
    file: $PWD/secrets/postgres_db.txt # put postgresql db name in this file
  postgres_password:
    file: $PWD/secrets/postgres_password.txt # put postgresql password in this file
  postgres_user:
    file: $PWD/secrets/postgres_user.txt # put postgresql username in this file
