---
title: "Project proposals"
---

# Introduction
For the Java Web Applications course final assignment, at least 3 proposals of feasible projects shall be defined and presented. Each member of the team shall present them to the rest and the project to work on shall be chosen by all team members.

# Projects proposals
## Data analysis platform

* **What is it expected to do?** Retrieve data from a data source and provide useful insights related to it
* **What is it for?** This allows to reach conclusions and take decisions based on actual facts and not speculations
* **Who is it for?** Any decision-making person regardless of their sector, be it market, entertainment, education, etc...
* **Why would it be interesting to do?** Because it would be an entry point to such a powerful sector as the Data Analysis, that uses Machine Learning to create models for categorization, prediction, foresight, etc...
* **How would it be done?**
    * Data acquisition would be done via API requests to public assets or using web scappers
    * Data engineering would be done with ETL (Extract, Transform and Load) processes
    * Data persistency would be achieved with relational databases (i.e. SQL, MariaDB...) for event-driven records (i.e. time-based information and historical data), or non-relational databases (noSQL, MongoDB, DynamoDB...) for any other type of document-based data (i.e. Information of movies, shows, sports teams, etc...)
    * Data representation would be done with a web application capable of graphically represent data sets. The user shall be able to modify the scope of the represented data and properly drill-down to obtain insight information

## 