project:
  type: website

filters:
  - include-code-files

website:
  # Website info
  title: "CIFO - Web Applications"
  site-url: https://protossgp32.github.io/CIFO-Web-Applications

  # Repository info
  repo-url: https://github.com/protossgp32/CIFO-Web-Applications
  repo-subdir: docs/quarto-examples
  repo-actions: [edit, issue]

  # Navigation bar
  navbar:
    # Left side
    left:
      - text: Home
        file: index.qmd
      - sidebar:devops-guides
      - sidebar:java-exercises
      - sidebar:walkthrough
      - text: About
        file: about.qmd

    # Right side
    right:
      - icon: github
        href: https://github.com/protossgp32
        aria-label: GitHub

        
  # Sidebars
  sidebar:
    # Categories
    - id: devops-guides
      title: "DevOps guides"
      style: "docked"
      contents: devops-guides/**

    - id: java-exercises
      title: "Java exercises"
      style: "docked"
      contents: java-exercises/**

    - id: walkthrough
      title: "Walkthrough"
      style: "docked"
      contents: walkthrough/**

  # Page Footer
  page-footer:
    center:
      - text: "About"
        file: about.qmd

  # Search options
  search:
    location: navbar
    type: overlay

  # Look and feel options
  reader-mode: true
  

format:
  html:
    # Theme options
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    # Table of Contents options
    toc: true
    # Code snippets options
    code-line-numbers: true
    code-overflow: scroll