project:
  type: website

filters:
  - include-code-files

editor:
  render-on-save: true

website:
  # Website info
  title: "CIFO - Web Applications"
  site-url: https://protossgp32.github.io/CIFO-Web-Applications

  # Repository info
  repo-url: https://github.com/protossgp32/CIFO-Web-Applications
  repo-subdir: docs/quarto-examples
  repo-actions: [edit, issue]

  # Navigation bar
  navbar:
    # Left side
    left:
      - text: Home
        file: index.qmd
      - sidebar:devops-guides
      - sidebar:java-exercises
      - sidebar:project-management
      - sidebar:team-projects
      - sidebar:miscellaneous
      - sidebar:walkthrough
      - text: About
        file: about.qmd

    # Right side
    right:
      - icon: github
        href: https://github.com/protossgp32
        aria-label: GitHub

        
  # Sidebars
  sidebar:
    # Categories
    - id: devops-guides
      title: "DevOps guides"
      style: "docked"
      contents: devops-guides/**

    - id: java-exercises
      title: "Java exercises"
      style: "docked"
      contents: java-exercises/**

    - id: walkthrough
      title: "Walkthrough"
      style: "docked"
      contents: walkthrough/**
    
    - id: team-projects
      title: "Team projects"
      style: "docked"
      contents: team-projects/**

    - id: project-management
      title: "Project Management"
      style: "docked"
      contents: project-management/**

    - id: miscellaneous
      title: "Miscellaneous"
      style: "docked"
      contents: miscellaneous/**

  # Page Footer
  page-footer:
    center:
      - text: "About"
        file: about.qmd

  # Search options
  search:
    location: navbar
    type: overlay

  # Look and feel options
  reader-mode: true
  page-navigation: true
  

format:
  html:
    # Theme options
    theme:
      light: cosmo
      #light: [cosmo, theme.scss]
      dark: superhero
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    # Table of Contents options
    toc: true
    # Code snippets options
    code-line-numbers: true
    code-overflow: scroll