project:
  type: website

website:
  title: "CIFO - Web Applications"

  # Navigation bar
  navbar:
    left:
      - text: Home
        file: first-project/index.qmd
      - sidebar:devops-guides
      - sidebar:java-exercises
      - sidebar:walkthrough
      - text: About
        file: first-project/about.qmd
        
  # Sidebars
  sidebar:
    - id: devops-guides
      title: "DevOps guides"
      style: "docked"
      contents: devops-guides/**

    - id: java-exercises
      title: "Java exercises"
      style: "docked"
      contents: java-exercises/**

    - id: walkthrough
      title: "Walkthrough"
      style: "docked"
      contents: walkthrough/**

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true