project:
  type: website

website:
  title: "CIFO - Web Applications"
  navbar:
    left:
      - href: first-project/index.qmd
        text: Home
      - text: DevOps guides
        menu:
        - href: devops-guides/mint-vm-provisioning.qmd
          text: VM provisioning
      - href: walkthrough/walkthrough.qmd
        text: Walkthrough
      - href: first-project/about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true