project:
  type: website

website:
  title: "first-project"
  navbar:
    left:
      - href: first-project/index.qmd
        text: Home
      - href: walkthrough/walkthrough.qmd
        text: Walkthrough
      - href: first-project/about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true