name: Library Manager Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - java-exercises/spring-boot-projects/spring-boot-lab-0/approach_1/**


jobs:
  build:
    name: Build and analyse code
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      #  with:
      #    fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      #- name: Set up JDK 17
      #  uses: actions/setup-java@v1
      #  with:
      #    java-version: 17
      #- name: Cache Maven packages
      #  uses: actions/cache@v1
      #  with:
      #    path: ~/.m2
      #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #    restore-keys: ${{ runner.os }}-m2
          
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 17
          checkout-fetch-depth: 0
          
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar        
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          LIBRARY_MANAGER_SONARQUBE_PROJECT_KEY: ${{ secrets.LIBRARY_MANAGER_SONARQUBE_PROJECT_KEY }}
          LIBRARY_MANAGER_PATH: java-exercises/spring-boot-projects/spring-boot-lab-0/approach_1
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage -Dsonar.projectKey=${LIBRARY_MANAGER_SONARQUBE_PROJECT_KEY} -Dsonar.projectBaseDir=${LIBRARY_MANAGER_PATH} -f ${LIBRARY_MANAGER_PATH}/pom.xml
