name: Library Manager Scan

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - java-exercises/spring-boot-projects/spring-boot-lab-0/approach_1

jobs:
  sonarqube_scan:
    name: SonarQube scan
    runs-on: ubuntu-latest
    steps:          
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 17
          fetch-depth: 0

      - name: Build Maven project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_PATH: "java-exercises/spring-boot-projects/spring-boot-lab-0/approach_1/pom.xml"
        # Avoid verify for now, until workflow is stable
        run: mvn -B clean compile -f ${PROJECT_PATH}

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Official SonarQube Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarqube-scan-action@a6ba0aafc293e03de5437af7edbc97f7d3ebc91a
        uses: SonarSource/sonarqube-scan-action@v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          # Additional arguments to the sonar-scanner
          args: >
            -Dsonar.verbose=false
            -Dsonar.projectKey=ProtossGP32_CIFO-Web-Applications_AYcZKPmoYGaZKjBqbseC
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: java-exercises/spring-boot-projects/spring-boot-lab-0/approach_1 # optional, default is .
