name: Library Manager Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - java-exercises/spring-boot-projects/spring-boot-lab-0/approach_1

jobs:
  sonarqube_scan:
    name: SonarQube scan
    runs-on: ubuntu-latest
    steps:
      - name: Official SonarQube Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarqube-scan-action@a6ba0aafc293e03de5437af7edbc97f7d3ebc91a
        uses: SonarSource/sonarqube-scan-action@v1.2.0
        with:
          # Additional arguments to the sonar-scanner
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: java-exercises/spring-boot-projects/spring-boot-lab-0/approach_1 # optional, default is .
